apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec: #Defines the deployment behivour
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: #Define the POD behivour
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "120Mi"
            cpu: "50m"
        ports:
        - containerPort: 3015
